var username;
var myName = "Shehzad Munir";
var message;
message = "Hello World";
alert(message);
var stuName = "Jhone Doe";
var stuAge = "15 years old";
var stuCert = "Certified Mobile Application Development";
alert(stuName);
alert(stuAge);
alert(stuCert);
var pizza = "PIZZA\nPIZZ\nPIZ\nPI\nP";
alert(pizza);
var email = "shehzadbaloch984@gmail.com";
alert("My email address is : " + email);
var book = "A Smarter way to learn JavaScript";
alert("I am trying to learn from the Book: " + book);
document.write("Yah! I can write HTML content through JavaScript");
var design = "“▬▬▬▬▬▬▬▬▬ஜ ۩۞۩ ஜ▬▬▬▬▬▬▬▬▬”";
alert(design);
//completed